### ISSUE TITLE
Missing requirement for phpdocumentor/reflection-docblock

### ISSUE THREAD

**Issue by dariusj18** [allansun/kubernetes-php-runtime#4]
The `AbstractModel` class attempts to use PhpDocExtractor on line 56, however apparently to use that class you need to require `phpdocumentor/reflection-docblock`.

**Comment by allansun** [comment]
That was not phpdocumentor/reflection-docblock
It was Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor which was correctly included.

**Comment by dariusj18** [comment]
The error I ran into was when PhpDocExtractor is instantiated, https://github.com/symfony/symfony/blob/master/src/Symfony/Component/PropertyInfo/Extractor/PhpDocExtractor.php#L62 throws an error if I didn't require `phpdocumentor/reflection-docblock`

`symfony/property-info` treats `phpdocumentor/reflection-docblock` as a soft requirement (I think you may have not seen the error because it is in require-dev), however this library seems to need it.

**Comment by allansun** [comment]
You are absolutely correct indeed!

Sorry I didn't notice that, seems I didn't use the --no-dev option even in our production environment.

The required package is not included in composer.json, hence I created a new version v1.0.6 to rectify this problem.

I will also submit a bug report to Symfony

**Comment by allansun** [comment]
https://github.com/symfony/symfony/issues/35874

Submitted the bug and see what they say

**Comment by allansun** [comment]
According to [reply from Symfony](https://github.com/symfony/symfony/issues/35874#issuecomment-591799814): We don't include optional packages in the require section of the package to avoid pulling too many deps when they are not strictly needed. Instead, we have a mechanism (as you pointed) that throws a nice error telling you how to fix the issue.

Apparently what I've just done (added it to our own composer.json) is the correct way to do it.
